upgrade uglify and check result to throw error
Footage-Firm/asset-processor pull request #27
Opened 2021-11-22 18:58 UTC by antlsung

2021-11-22 23:17 UTC, aarsilv requested changes
I think I may have found a bug when you're setting `objectToMinify` properties from the files.

2021-11-22 23:17 UTC, aarsilv commented on lib/assetProcessor.js
> +                        objectToMinify['file'] = fs.readFileSync(file, "utf8");
I'm guessing you don't want `'file'` to be a string literal, as this will just overwrite that one key each time in the loop. Perhaps you meant `objectToMinify[file]` (variable reference for the property instead of string)

2021-11-23 14:16 UTC, antlsung commented on lib/assetProcessor.js
> +                        objectToMinify['file'] = fs.readFileSync(file, "utf8");
thanks for this haha ^ not sure how i missed that

2021-11-23 17:14 UTC, aarsilv approved these changes
Approving!

Since NPM is folder-based, one way to test this out would be to copy your repo into the `node_modules` folder of the repository you are working with. Then it would use this code as the module. 

If you're working on the contributor portal (wasabi) I _think_ you could do `USE_CDN=true` when starting your server to make it use the asset processor.

2021-11-23 17:14 UTC, aarsilv commented on lib/assetProcessor.js
> +                        objectToMinify[file] = fs.readFileSync(file, "utf8");
:+1:

2021-12-01 16:25 UTC, merged

2021-12-01 17:15 UTC, antlsung commented
no problem, thanks for helping out! I actually just published it to NPM

2021-12-01 18:01 UTC, aarsilv commented
🎉 Awesomesauce! 🎉