[Bugfix] Fixing to work with Node16
Footage-Firm/asset-processor pull request #32
Opened 2023-01-06 14:44 UTC by alaughlin

This upgrades asset-processor to compatible with Node16. The biggest issue was the `knox` package, as it doesn't seem to be compatible with newer versions of Node and was silently failing. This swaps it out with the `aws-sdk` package. The changes for that can be found in `s3.js`

This commit also contains some cleanup in `assetProcessor.js`, mainly converting most of the code to use arrow functions to cut down on the number of scoping hacks we were using (passing `this` around everywhere) and to just bring this code in line with more modern conventions (sorry Aaron... 😂)

There's definitely some more cleanup that can be done but I didn't want to go overboard here, and I think we need to consider removing our reliance on this package altogether.

2023-01-06 14:54 UTC, antlsung approved these changes
beautiful, nice job

2023-01-06 15:12 UTC, dsellers-sb approved these changes
LGTM! thanks for doing this!

2023-01-06 15:16 UTC, alaughlin commented on lib/s3.js
>          headers['x-amz-acl'] = 'public-read';
yes, or if it's false-y (since it supports either a bool or an object being passed in from upstream)

2023-01-06 16:05 UTC, nguyen102 commented on lib/s3.js
> +        headers['x-amz-acl'] = 'private';
HI @alaughlin! Couldn't you just set  this on line 147? This will save you from setting them agein from line 150 to 155. 
```
let headers = {"x-amz-acl": 'private'}
```

I just saw this PR in my email, and I figure I take a look for old time sake :)

2023-01-06 16:05 UTC, stephanie-storyblocks approved these changes
Thank you for the clean up and nice find!!

2023-01-06 16:06 UTC, alaughlin commented on lib/s3.js
> +        headers['x-amz-acl'] = 'private';
ah good catch! this was a lazy copy/paste from another repo and I didn't notice that

2023-01-06 16:16 UTC, kimquill commented on lib/s3.js
> +        headers['x-amz-acl'] = 'private';
OMG HI @nguyen102 !

2023-01-06 16:18 UTC, nguyen102 commented on lib/s3.js
> +        headers['x-amz-acl'] = 'private';
Hi @kimquill! I'm glad to see some familiar faces at SB!

2023-01-06 16:20 UTC, Oconis commented on lib/s3.js
> +        headers['x-amz-acl'] = 'private';
This is my new favorite PR thread. I love a good old SB reunion!

2023-01-06 16:23 UTC, alaughlin commented on lib/s3.js
> +        headers['x-amz-acl'] = 'private';
lol best PR thread

2023-01-06 16:23 UTC, nguyen102 commented on lib/s3.js
> +        headers['x-amz-acl'] = 'private';
Hi Ben!

2023-01-06 16:27 UTC, neelmehta commented on lib/s3.js
> +        headers['x-amz-acl'] = 'private';
Hey All!

2023-01-06 16:28 UTC, kimquill commented on lib/s3.js
> +        headers['x-amz-acl'] = 'private';
is everyone just getting email updates what's happening

2023-01-06 17:16 UTC, daniellehicks approved these changes
LGTM!

2023-01-06 17:19 UTC, neelmehta commented on lib/s3.js
> +        headers['x-amz-acl'] = 'private';
Yup it is. I think this is a public repo?

2023-01-06 19:50 UTC, aarsilv requested changes
This is a great start, but since you are going in and cleaning things up, I think you could do so in a consistent fashion so as not to confuse the next developers that work on this. This code will probably be used for another decade, based on historical trends.

The main reason I'm requesting changes is that you're introducing an already out-of-date AWS SDK package. AWS has a v[3 version](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/) of their API, where--in addition to receiving updates and whatnot--you can also just import the component you need (in this case S3). AWS has changed things to break old SDK versions (even just outdated minor versions) so I'd stay ahead of this by at least resetting to the latest version.

Another reason I'm requesting changes is that there seems to be some manual hacks to work around the mixing of callback and promise style functions. However, node has built-in utilities that make this a snap, and we should just use those. We're not the first company that needs to merge those two world!

Lastly, for the code you modified, consider better cleaning it up. This includes:
* simpler arrow functions for one-line bodies
* leveraging optional chaining
* eliminating unnecessary anonymous functions
* consistent string syntax

I do appreciate you proactively cleaning up the other areas besides just the S3 part you worked on. That helps fight code rot and entropy. Just asking that you take it up one more notch, so that asset processor can continue to be a reliable workhouse that thanklessly powers a website that gets millions of views and generates millions in revenue every month.

2023-01-06 19:50 UTC, aarsilv commented on package.json
> -    "knox": "^0.8.9",
oh man, `knox` predates the aws SDK (at least for multi-part uploads, if not all). Glad to see it finally go!

2023-01-06 19:50 UTC, aarsilv commented on package.json
> +    "aws-sdk": "^2.722.0",
This SDK is already out of date, AWS has a v3 SDK!

2023-01-06 19:50 UTC, aarsilv commented on lib/s3.js
> +S3.prototype.putFile = async function(sourcePath, targetPath, makePrivateOrHeaders) {
So much overlap with `putBuffer()` since you are in here; you could just make one base function that the two call out to.

2023-01-06 19:50 UTC, aarsilv commented on lib/s3.js
> +            // We won't propagate not found errors
great call!

2023-01-06 19:50 UTC, aarsilv commented on lib/s3.js
> +    for (const [key, value] of Object.entries(headers)) {
nice!

2023-01-06 19:52 UTC, aarsilv commented
Also, @neelmehta, @nguyen102, @Oconis, @kimquill, @stephanie-storyblocks, @alaughlin, HI FRIENDS! So fun to see y'all in this thread, and I miss y'all dearly! Come out and play in Ouray any time!

2023-01-06 19:53 UTC, aarsilv commented
@daniellehicks & @dsellers-sb: https://twitter.com/iamdevloper/status/397664295875805184?s=20&t=KYnwhn56gqjcZqI-b_QS-g

2023-01-06 20:04 UTC, kimquill commented
@aarsilv 
> This code will probably be used for another decade, based on historical trends.

💀 💀 💀

2023-01-06 20:09 UTC, alaughlin commented on lib/assetProcessor.js
> -            self.emit('minifyEnded', {type: 'js', files: jsFiles});
I couldn't find anything relying on it at this point

2023-01-06 20:11 UTC, alaughlin commented on lib/assetProcessor.js
> -AssetProcessor.prototype.processImages = function(callback) {
I did check and we're not using it anywhere upstream at least. If you think we should keep it around I can add it back though!

2023-01-06 20:15 UTC, alaughlin commented on lib/assetProcessor.js
> +    try {
I did that because it's either that or adding try/catch to the  multiple places in upstream code calling in (in this case, 2 different async.auto steps, and since async.auto cannot properly handle promise rejections, a try/catch is needed). happy to make that change if you think it's clearer.

2023-01-06 20:16 UTC, alaughlin commented on lib/assetProcessor.js
> +                //need to resolve files relative to root
dunno why that happened 😂

2023-01-06 20:17 UTC, alaughlin commented on lib/assetProcessor.js
> + async function _handleAsync(func) {
oh, I'll look into those, thanks!

2023-01-06 20:22 UTC, alaughlin commented
to all the SB alumni, thanks for stopping by!!! great to see y'all

@aarsilv thanks for all the feedback! hard disagree on your another decade of use prediction though 🙃

2023-01-06 21:07 UTC, alaughlin commented on lib/assetProcessor.js
> +    try {
ignore my above comment! this is more cleanly resolved using `util.callbackify`, will fix this up

2023-01-06 22:55 UTC, aarsilv commented on package.json
> +    "aws-sdk": "^2.722.0",
Note One watch-out is that V3 changes the way AWS authenticates, so instead of passing keys to the SDK you may need the right environment variables set or credentials file saved or something.

2023-01-06 23:00 UTC, aarsilv commented on lib/assetProcessor.js
> -AssetProcessor.prototype.processImages = function(callback) {
Naw as long as you checked its good to axe 🪓

2023-01-09 16:27 UTC, alaughlin commented on package.json
> +    "aws-sdk": "^2.722.0",
all set! it's been upgraded

2023-01-09 16:30 UTC, alaughlin commented
@aarsilv I believe I've addressed all the things you commented on, I think you owe me a second pass now 😂

2023-01-09 19:14 UTC, alaughlin commented on lib/s3.js
> + * @param {string} bucket
forgot that, thanks!

2023-01-09 19:14 UTC, alaughlin commented on test/test-assetProcessor.js
> +        region: process.env.S3_REGION,
yep!

2023-01-09 19:19 UTC, alaughlin commented
@stephanie-storyblocks because this was silently failing before I'm not sure if there was any other way we could have caught this. Checking staging _before_ going to prod should tell us if something went wrong - because if there are any frontend changes, staging will attempt to find the bundled assets with the correct hash, and fail to fetch them if the deploy pipeline was unable to generate them.

Since we should always be checking staging before going to prod, I'm ok with that being the valid way to verify that assets were properly uploaded to S3. I think the longer term, real fix is to deprecate this package altogether and move all this logic directly into wasabi.

2023-01-19 13:44 UTC, merged